stages:
 - javadoc
 - sonar

javadoc:
 stage: javadoc
 script:
   - "mvn javadoc:aggregate --fail-never"
   - "mkdir -p /usr/share/nginx/javadoc/${PWD##*/}"
   - "cp -r ./target/site/apidocs /usr/share/nginx/javadoc/${PWD##*/}"
 tags:
  - java
 only:
  - develop

sonar:
 stage: sonar
 script:
  - mvn -q -Dmaven.multiModuleProjectDirectory=$MAVEN_HOME clean org.jacoco:jacoco-maven-plugin:prepare-agent test checkstyle:checkstyle sonar:sonar -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.branch.target=develop
 tags:
  - java
 only:
  - develop