stages:
 - build
 - sonar

build:
 stage: build
 script: "mvn clean package -B -Dmaven.test.skip=true"
 tags:
  - java


sonar:
 stage: sonar
 script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent  sonar:sonar
 tags:
  - java
 only:
  - develop