stages:
 - build
 - sonar

build:
 stage: build
 script: "mvn clean package -B -Dmaven.test.skip=true"
 tags:
  - java


sonar:
 stage: sonar
 script:
  - mvn -q -Dmaven.multiModuleProjectDirectory=$MAVEN_HOME clean org.jacoco:jacoco-maven-plugin:prepare-agent test checkstyle:checkstyle sonar:sonar -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.branch.target=master
 tags:
  - java
 only:
  - develop