stages:
 - build
 - sonar

build:
 stage: build
 script: "mvn clean package -B -Dmaven.test.skip=true"
 tags:
  - java

javadoc:
 stage: javadoc
 script:
   - "mvn javadoc:aggregate --fail-never"
   - "mkdir -p /usr/share/nginx/javadoc/${PWD##*/}"
   - "cp -r ./target/site/apidocs /usr/share/nginx/javadoc/${PWD##*/}"
 tags:
  - java
 only:
  - develop

sonar:
 stage: sonar
 script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar
 tags:
  - java
 only:
  - develop