stages:
 - build
 - sonar

build:
 stage: build
 script:
 - "mvn clean package -B -Dmaven.test.skip"
 only:
 - develop
 tags:
 - java

sonar:
 stage: sonar
 script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.test.failure.ignore=true -Ptest -Dsonar.inclusions=**/service/**,**/biz/**,**/dao/**
 only:
 - develop
 tags:
 - java
 allow_failure: true
